export const words = [
  // 英語
  "Not today",
  "I almost said it",
  "Maybe later",
  "I held it in",
  "Almost",
  "Not yet",
  "I couldn't",
  "Maybe tomorrow",
  "I stopped myself",
  "Almost there",
  "Not now",
  "I hesitated",
  "Maybe next time",
  "I held back",
  "Almost spoke",
  "I wanted to",
  "But I didn't",
  "Maybe someday",
  "I kept quiet",
  "Not this time",
  "I swallowed it",
  "Almost told you",
  "I held my breath",
  "Maybe never",
  "I let it go",
  
  // 日本語
  "今日は言わない",
  "また今度",
  "言いかけてやめた",
  "もう少し待って",
  "まだ言えない",
  "言わなかった",
  "ためらった",
  "飲み込んだ",
  "また今度でいい",
  "言えなかった",
  "今日はやめておく",
  "もう少し後で",
  "言わずに終わった",
  "また今度にしよう",
  "言うのをやめた",
  "今日はやめとく",
  "言わないでおいた",
  "また今度で",
  "言いそびれた",
  "今日は見送る",
  "言わないことにした",
  "また今度に",
  "言うのをためらった",
  "今日はやめて",
  "言わずに済ませた",
];

